version: '3'
services:
  django:
    container_name: django
    build:
      context: ./superlists
      dockerfile: Dockerfile
    links:
      - selenium
    ports:
      - 8000:8000

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - django


