# not working yet
# version: "2"

# services:
#   django:
#     build: .
#     volumes:
#       - ".:/code"
#     ports:
#       - "8000:8000"
#     links:
#       - selenium_hub

#   selenium_hub:
#     container_name: selenium_hub
#     image: selenium/hub
#     ports:
#       - "4444:4444"

#   selenium_chrome:
#     container_name: selenium_chrome
#     image: selenium/node-chrome-debug
#     environment:
#       - HUB_PORT_4444_TCP_ADDR=selenium_hub
#       - HUB_PORT_4444_TCP_PORT=4444
#     ports:
#       - "5900:5900"
#     depends_on:
#       - selenium_hub

#   selenium_firefox:
#     container_name: selenium_firefox
#     image: selenium/node-firefox-debug
#     environment:
#       - HUB_PORT_4444_TCP_ADDR=selenium_hub
#       - HUB_PORT_4444_TCP_PORT=4444
#     ports:
#       - "5901:5900"
#     depends_on:
#       - selenium_hub
  

version: '3'
services:
  django:
    container_name: django
    build:
      context: ./superlists
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    links:
      - selenium
    ports:
      - 8000:8000

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - django


